travis:
  secure:
    BINSTAR_TOKEN: oVfqWwy9+Lao5nIE1GS/Z3RGyP+Klw4bqH+wimL5zvsevdzqFfn+OrRJ1a2lrVQ5t2Ct0Cu6V0PDISBsvrMYujZw2Br17vJzjryS8213YwhGAC5hpNWaku7riIim3+UPXCh1c7odH5LUsmqxxakGrquQ7eqGXDojK0CLZ9Jzg6XGihAsxsc5eWKkiDRoAAJk/17l9dzXqQIJrNHchTKPjjdEY2+LRDmQVneBZrNp29WgafgQGnM7339C4KcC5tizvtWtftkOImIbQfj0ly+BObRJuREoeCeIwu8cgxe3RXFf2TIgn2iV+6qWTs9SYAyRel+dsaI0UHvZo2YYa2vjSM1kqLefTbOh8OD9sEhcf3JTqgY0cAQOvdDUthmBeAwvRWzzOx1JeMoAJwH99JVNZNVuFgMcIaK3n6qFbTt/gKrP/BuWMCTHR0Te1pYEm0v/6k33ZaW21bT1sBj8W8YcHrlqnszhTydDcwpVDwlVFB7q8Zbl0KK/jcNosEsyj2gi1QoFJgPR7HeGVk7v4udsGMsuE1sfzUYr8iq563zd91ydlRMZs+sa3SfHFUiUwkRFU2O/OnB3k2oysdJMBmWmah/Gb6nUgr/3rjWPuPYA4yb9aEr02IzwG/uCVxsKQzFYec9dKtHrasmuyFDKyaZDspMOftOrSHkrtKLFODuwFOY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
