travis:
  secure:
    BINSTAR_TOKEN: krDAXqWoY7fWZ9S8Taa3PsZN6rTQFqdSiXDPV8kQFdBUjBWb8lyZKc53t6tBnggKQl28CU4ioxflCKNd+TGx3nNiU6An8GinEqsFPhW517lcd+2XKSaxww6N9C9LlYMzRsylZ/mmazQRwXlKXhWXZudyYaFBseZVhvLGP3yod5vqCQL/Prrnc0L3qGgs4un64Ac17FryyfeskW9XKFEjVxtCmfJG2MOu8eLn251+/6btjPANHlArQPy/24E5ovUBMtytHu9K5J77kezKadkQIE8h27DI3OCH/JvIc6B6MI/4veT2LzJ929yHOKW4dRpLn3mMsG4IclCoc5FJ0OPAdl5nE+I71Pwmf+sTByeEf/Kl6brpVUeHOTpS+7WOcfx4I0vwRrbwGzRJl5Rt/A6MmPoJ9vsPqZb4UcxtLTE48CD8iH2ee6GYyunGdIc9iaeHpExTHThwt7k9ULDFnhMh6zmxV/RYGWW728wsQv+4TkOAg0EMkhPWMSfLwnSPC31W++QlWs+0Dr3K8ww9cqvWEQszKRDyaLZtOBe6XSOn6wO4XmNULlL0m+b+HLarmM6l6afLDKZRIY4GNpSK++5ph4kxVUdjhPj498bF7fAFZPylBi35FipjF4uHufQQ6rqpn7Bt9GbYrp+BkUh7FmqnTSbokyjSUqUXXEqsDaPomK4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
